name: Test and Build

#Define on which brances does it work (makes the tests)
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

#Define the permissions that it'll have
permissions:
  contents: read

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 #Chequeo de la rama (el codigo)
      - name: Set up Python 3.10 #Instalar python
        uses: actions/setup-python@v4 #Todas las dependecias y cosas necesarias para ejecutar py
        with:
          python-version: '3.10'

      - name: OpenCommit â€” improve commits with AI
        uses: di-sukharev/opencommit@github-action-v1.0.2
        with:
          GITHUB_TOKEN: ''

      #Instalar dependencias de los requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Basic_Example/requirements.txt 

      #Ejecutar pruebas con pytest
      - name: Test with pytest
        run: |
          cd Basic_Example
          pytest
